syntax = "proto3";

package resourcemaster.v1;

message ListResourceMasterRequest {}

message ListResourceMasterResponse {
  repeated ResourceMaster resource_masters = 1;
}
message ResourceMaster {
  string id = 1;
  string code = 2;
  string name = 3;
  string description = 4;
  Icon icon = 5;
  repeated string categories = 6;
}

message Icon {
  IconType type = 1;
  IconColor color = 2;
}

enum IconType {
  ICON_TYPE_UNSPECIFIED = 0;
  ICON_TYPE_FIRE = 1;
  ICON_TYPE_TEAM = 2;
  ICON_TYPE_BOX = 3;
  ICON_TYPE_FUNCTION = 4;
}

enum IconColor {
  ICON_COLOR_UNSPECIFIED = 0;
  ICON_COLOR_RED = 1;
  ICON_COLOR_GREEN = 2;
  ICON_COLOR_BLUE = 3;
  ICON_COLOR_YELLOW = 4;
  ICON_COLOR_ORANGE = 5;
  ICON_COLOR_PURPLE = 6;
  ICON_COLOR_PINK = 7;
  ICON_COLOR_BROWN = 8;
  ICON_COLOR_GRAY = 9;
}

message Attribute {
  string code = 1;
  string name = 2;
  ValueType value_type = 3;
  bool is_array = 4;
  int32 order_no = 5;
}

enum ValueType {
  VALUE_TYPE_UNSPECIFIED = 0;
  VALUE_TYPE_STRING = 1;
  VALUE_TYPE_NUMBER = 2;
  VALUE_TYPE_BOOLEAN = 3;
}

service ResourceMasterService {
  rpc ListResourceMaster (ListResourceMasterRequest) returns (ListResourceMasterResponse);
}
