version: "3"

dotenv:
  - .env
  - core/.env

tasks:
  dev:api:
    dir: ./api
    cmds:
      - deno run -A src/main.ts --watch
  gen:kysely:
    dir: ./api
    cmd: |
      echo "import 'npm:pg@^8.11.3'; import 'npm:kysely-codegen@^0.11.0';" | \
      deno run -A npm:kysely-codegen@^0.11.0 - \
      kysely-codegen --dialect=postgres --out-file ./src/dbtype.ts --camel-case
    silent: true
  ngrok:
    cmd: ngrok http 8001
  dev:slack:
    dir: ./slack
    cmd: deno run -A ./src/main.ts
  db:migrate:
    dir: ./db
    cmd: PGPASSWORD=$DB_PASS psqldef -h $DB_HOST -U $DB_USER $DB_NAME --enable-drop-table < schema.sql
