version: '3'

dotenv:
  - .env
  - core/.env

tasks:
  setup:sqlc:
    cmd: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
  setup:pubsub-emulator:
    cmd: gcloud components install pubsub-emulator
  setup:
    cmds:
      - task setup:sqlc
      - task setup:pubsub-emulator
  init:pubsub:
    dir: ./scripts
    cmd: echo && {{.EMULATOR_HOST}} go run ./init_pubsub.go
  run:pubsub:

    cmd: gcloud beta emulators pubsub start --project=$GCLOUD_PROJECT_ID
  run:api:
    dir: ./core
    cmds:
      - go run ./main.go --mode api --port 8080
  run:worker:
    dir: ./core
    vars:
      EMULATOR_HOST:
        sh: gcloud beta emulators pubsub env-init --project=$GCLOUD_PROJECT_ID | sed -e 's/export //'
    # cmd: {{.EMULATOR_HOST}}
    cmds:
        - echo "starting worker" && {{.EMULATOR_HOST}} go run ./main.go --mode worker --port 8081
  test:publish:
    dir: ./scripts
    vars:
      EVENT_TYPE: '{{.EV_TYPE}}'
      WORKER_PORT: 8081
      EMULATOR_HOST:
        sh: gcloud beta emulators pubsub env-init | sed -e 's/export //'
    cmd: echo "publishing message" && {{.EMULATOR_HOST}} go run ./publish.go --evType={{.EVENT_TYPE}} --workerPort={{.WORKER_PORT}}
  test:publish:incident:
    cmds:
      - task: test:publish
        vars: { EV_TYPE: incident }
  test:publish:role:
    cmds:
      - task: test:publish
        vars: { EV_TYPE: role }
  test:publish:all:
    cmds:
      - task: test:publish:incident
      - task: test:publish:role
  gen:connect:
    dir: ./web
    cmd: pnpm gen
    silent: true
  gen:sqlc:
    dir: .
    cmd: sqlc generate
  gen:
    deps:
      - gen:connect
      - gen:sqlc
  db:migrate:
    dir: ./db
    cmd: PGPASSWORD=$DB_PASS psqldef -h $DB_HOST -U $DB_USER $DB_NAME --enable-drop-table < schema.sql