version: "3"
dotenv: [".env"]
tasks:
  deploy-config-layer:
    cmds:
      - rm ./config-layer.zip
      - zip -Dj ./config-layer.zip ./config.yaml
      - >
        aws lambda publish-layer-version
        --profile $AWS_PROFILE
        --region $AWS_REGION
        --no-cli-pager
        --layer-name $CONFIG_LAYER_NAME
        --zip-file fileb://./config-layer.zip
        --compatible-runtimes nodejs20.x
        --compatible-architectures x86_64 arm64
  run-bot:
    dir: ./bot-function
    cmds:
      - rm -rf ./dist/*
      - npm run build
      - npm start
  deploy-bot:
    dir: ./bot-function
    cmds:
      - rm -rf ./dist/*
      - npm run build
      - zip -Dj ./dist/bot-function.zip ./dist/main.mjs
      - >
        aws lambda update-function-code
        --profile $AWS_PROFILE
        --region $AWS_REGION
        --no-cli-pager
        --function-name $BOT_FUNCTION_NAME
        --zip-file fileb://./dist/bot-function.zip
  log-bot:
    dir: ./bot-function
    cmd: >
      aws logs tail
      /aws/lambda/$BOT_FUNCTION_NAME
      --profile $AWS_PROFILE
      --region $AWS_REGION
