edition = "2023";

import "models/user/v1/user.proto";

package api.incident.v1;

message Assignment {
	string incident_id = 1;
  string role_slot_id = 2;
	string role_id = 3;
	string role_name = 4;
	string role_code = 5;
	string role_abbr = 6;
	string role_color = 7;
	models.user.v1.User user = 8;
}

message ListAssignmentsRequest {
	string incident_id = 1;
}

message ListAssignmentsResponse {
  repeated Assignment assignments = 1;
}

service AssignmentService {
  rpc ListAssignments (ListAssignmentsRequest) returns (ListAssignmentsResponse);
}
