services:
  firestore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: >
      gcloud beta emulators firestore start
      --host-port=0.0.0.0:8080
      --project=demo-incident-buddy
    networks:
      - incident-buddy

networks:
  incident-buddy:
    name: incident-buddy
