edition = "2023";

package api.incident.v1;

import "google/protobuf/timestamp.proto";

message Incident {
  string id = 1;
  string code = 2;
  string title = 3;
  string summary = 4;
	IncidentStatus latest_status = 5;
	google.protobuf.Timestamp declared_at = 6;
}

message IncidentStatus {
	string id = 1;
	string name = 2;
	IncidentStatusType type = 3;
	Color color = 4;
}

enum IncidentStatusType {
	INCIDENT_STATUS_TYPE_UNSPECIFIED = 0;
	INCIDENT_STATUS_TYPE_INVESTIGATING = 1;
	INCIDENT_STATUS_TYPE_DECLARED = 2;
	INCIDENT_STATUS_TYPE_ONGOING = 3;
	INCIDENT_STATUS_TYPE_CONVERGED = 4;
	INCIDENT_STATUS_TYPE_CLOSED = 5;
}

enum Color {
	COLOR_UNSPECIFIED = 0;
	COLOR_RED = 1;
	COLOR_GREEN = 2;
	COLOR_BLUE = 3;
}


message ListIncidentsRequest {}

message ListIncidentsResponse {
  repeated Incident incidents = 1;
}

message GetIncidentRequest {
	string id = 1;
}
message GetIncidentResponse {
	Incident incident = 1;
}

message UpdateIncidentTitleRequest {
	string id = 1;
	string title = 2;
}
message UpdateIncidentTitleResponse {}

message UpdateIncidentSummaryRequest {
	string id = 1;
	string summary = 2;
}
message UpdateIncidentSummaryResponse {}

service IncidentService {
	rpc GetIncident (GetIncidentRequest) returns (GetIncidentResponse);
  rpc ListIncidents (ListIncidentsRequest) returns (ListIncidentsResponse);
	rpc UpdateIncidentTitle (UpdateIncidentTitleRequest) returns (UpdateIncidentTitleResponse);
	rpc UpdateIncidentSummary (UpdateIncidentSummaryRequest) returns (UpdateIncidentSummaryResponse);
}
