edition = "2023";

package api.incident.v1;

message Incident {
  string id = 1;
  string code = 2;
  string title = 3;
  string description = 4;
}

message ListIncidentsRequest {}

message ListIncidentsResponse {
  repeated Incident incidents = 1;
}

message GetIncidentRequest {
	string id = 1;
}
message GetIncidentResponse {
	Incident incident = 1;
}

service IncidentService {
	rpc GetIncident (GetIncidentRequest) returns (GetIncidentResponse);
  rpc ListIncidents (ListIncidentsRequest) returns (ListIncidentsResponse);
}
