edition = "2023";

package api.authn.v1;

message AuthorizedUser {
  string id = 1;
  string email = 2;
}

message EmailAuthorizeRequest {
	string email = 1;
	string password = 2;
}

message EmailAuthorizeResponse {
	oneof result {
		AuthorizedResponse authorized = 1;
		UnauthorizedResponse unauthorized = 2;
	}
}

service AuthorizationService {
	rpc EmailAuthorize(EmailAuthorizeRequest) returns (EmailAuthorizeResponse);
}

message AuthorizedResponse {
	AuthorizedUser user = 1;
}
message UnauthorizedResponse {
	string message = 1;
}



